# Mod 6.5.2 Create Heatmaps for Weather Parameters

### For a basic heatmap, all we need to do is provide the following:
#### ---> latitudes and longitudes for the locations
#### ---> A measurement value for each latitude and longitude in the for of arrays
####       that have the same number of items in each array.

### Begin by importing our dependencies and Google API key, and then add
### our cities.csv file to a DataFrame.

In [1]:
# Import the dependencies
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import numpy as np

# Import the Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# Read our cities.csv file into a DataFrame
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hardoi,IN,23-08-29 18:45:41,27.4167,80.1167,82.74,69,4,3.67,clear sky
1,1,Adamstown,PN,23-08-29 18:43:13,-25.0660,-130.1015,62.42,84,100,8.81,light rain
2,2,Carnot,CF,23-08-29 18:45:41,4.9409,15.8665,68.95,97,88,4.03,overcast clouds
3,3,Bel Ombre,SC,23-08-29 18:45:42,-4.6167,55.4167,80.44,74,40,10.36,scattered clouds
4,4,Olyokminsk,RU,23-08-29 18:45:42,60.3736,120.4264,57.79,69,20,1.12,few clouds
5,5,Alice Springs,AU,23-08-29 18:42:01,-23.7000,133.8833,49.55,34,17,6.91,few clouds
6,6,Enewetak,MH,23-08-29 18:45:42,11.3474,162.3373,83.59,78,100,17.60,overcast clouds
7,7,Altamont,US,23-08-29 18:45:43,42.2068,-121.7372,67.78,55,20,3.44,haze
8,8,Margaret River,AU,23-08-29 18:44:33,-33.9500,115.0667,46.47,88,5,8.32,clear sky
9,9,Anadyr,RU,23-08-29 18:44:33,64.7500,177.4833,39.70,100,20,4.47,fog

In [3]:
# Get the data types.
city_data_df.dtypes

City_ID                  int64
City                    object
Country                 object
Date                    object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
dtype: object

In [4]:
len(city_data_df)

533

In [5]:
# First, tell gmaps to use your API key. You only need to configure gmaps to use your API key.
gmaps.configure(api_key=g_key)

## Generate Syntax for creating a Heat Map

### Next, create the heat map for the maximum temperature.

#### 1. Assign the locations to an array of latitude and longitude pairs. locations = [ latitude, longitude]
#### 2. Assign the weights variable to some values.
####     temperatures = # of arrays of equal length to the locations of the array length
#### 3. Assign the figure variable to the gmaps.figure() attribute. fig = gmaps.figure()
#### 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the location.
####     heatmap_layer = gmaps.heatmap_layer(locations, weights= temperatures)
#### 5. Add the heatmap layer. fig.add_layer(heatmap_layer)
#### 6. Call the figure to plot the data.

In [6]:
# Mod 6.5.3 Get Vacation Criteria

# A feature on the app that allows customers to search for locations they want to visit 
# based on temperature preferences.

# We need to prompt the user to enter the Minimum and Maximum temperature ranges as 
# floating-point decimal numbers to filter the city_data_df DataFrame.

# REWIND: Recall that you use the input() statement to prompt a user to enter information.
# To convert the input to a floating-point decimal number, wrap the input() statement
# with the float() method.

# Ask the customer to enter and minimum and maximum temperature value.
min_temp = float(input("What is the minimum fahrenheit temperature that you would like for your trip "))
max_temp = float(input("What is the maximum fahrenheit temperature that you would like for your trip "))

What is the minimum fahrenheit temperature that you would like for your trip 50
What is the maximum fahrenheit temperature that you would like for your trip 85

In [7]:
# Next, filter the "Max Temp" column in the city_data_df DataFrame using the .loc[] method.

# Filter the dataset to find the cities that fit the criteria
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hardoi,IN,23-08-29 18:45:41,27.4167,80.1167,82.74,69,4,3.67,clear sky
1,1,Adamstown,PN,23-08-29 18:43:13,-25.0660,-130.1015,62.42,84,100,8.81,light rain
2,2,Carnot,CF,23-08-29 18:45:41,4.9409,15.8665,68.95,97,88,4.03,overcast clouds
3,3,Bel Ombre,SC,23-08-29 18:45:42,-4.6167,55.4167,80.44,74,40,10.36,scattered clouds
4,4,Olyokminsk,RU,23-08-29 18:45:42,60.3736,120.4264,57.79,69,20,1.12,few clouds
6,6,Enewetak,MH,23-08-29 18:45:42,11.3474,162.3373,83.59,78,100,17.60,overcast clouds
7,7,Altamont,US,23-08-29 18:45:43,42.2068,-121.7372,67.78,55,20,3.44,haze
10,10,Badger,US,23-08-29 18:45:43,64.8000,-147.5333,62.82,86,75,0.00,broken clouds
11,11,Kodiak,US,23-08-29 18:45:44,57.7900,-152.4072,56.71,82,40,0.00,scattered clouds
12,12,Yellowknife,CA,23-08-29 18:40:24,62.4560,-114.3525,78.42,54,40,10.36,smoke

In [8]:
preferred_cities_df.count()

City_ID                410
City                   410
Country                407
Date                   410
Lat                    410
Lng                    410
Max Temp               410
Humidity               410
Cloudiness             410
Wind Speed             410
Current Description    410
dtype: int64

In [9]:
clean_df = preferred_cities_df.dropna()

## Get Travel Destination

### --> Don't add the hotel information to the preferred_cities_df DataFrame.

### ---> Make a cop of the preferred_cities_df DataFrame and name it hotel_df. 
###        For the hotel_df, keep the columns 'City', 'Country', 'Max Temp', 'Current Description',  'Lat', and 'Lng'
###        Add a new column to hotel_df DataFrame to hold the hotel name.

In [10]:
# Create DataFrame called hotel_df to store the hotel names along with the city, country, max temp, and coordinates.
hotel_df = clean_df[['City', 'Country', 'Max Temp', 'Current Description', 'Lat', "Lng"]].copy()
hotel_df['Hotel Name'] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hardoi,IN,82.74,clear sky,27.4167,80.1167,
1,Adamstown,PN,62.42,light rain,-25.0660,-130.1015,
2,Carnot,CF,68.95,overcast clouds,4.9409,15.8665,
3,Bel Ombre,SC,80.44,scattered clouds,-4.6167,55.4167,
4,Olyokminsk,RU,57.79,few clouds,60.3736,120.4264,
6,Enewetak,MH,83.59,overcast clouds,11.3474,162.3373,
7,Altamont,US,67.78,haze,42.2068,-121.7372,
10,Badger,US,62.82,broken clouds,64.8000,-147.5333,
11,Kodiak,US,56.71,scattered clouds,57.7900,-152.4072,
12,Yellowknife,CA,78.42,smoke,62.4560,-114.3525,

## Using the latitude and longitude and specific parameters, 

### use the Google Places Nearby Search request to retrieve a hotel 
### and add it to the 'Hotel Name' column.

#### Retrieve hotels from a nearby search

#### Set the parameters for a nearby search


## Nearby Search Requests

### A nearby search request is a HTTP URL of the following form:


## The Nearby Search request lets us perform these tasks:

### 1. Search for places within a specified area.
### 2. Refine the search using keywords and specifying the type of place we are searching for.
### 3. Use an API URL, where the output can be either XML or JSON.

## Specific Parameters Include:

### 1. Our API key.
### 2. A location, which will be the latitude and longitude.
### 3. A radius for the search. We'll keep our search to 5000 meters.
### 4. Type of place.

#### NOTE: see /developers.google.com/maps/documentation/places/web-services/supported_types

### REWIND: when we made a request with the OpenWeatherMap API, we added a
### base url with the city (city_url), to the request:
### city_weather = requests.get(city_url)

### The following base url is provide to retrieve the JSON format of the data:

### https:/maps.googleapis.com/maps/api/place/nearbysearch/json

## Passing Parameters in URLs

### Requests allow you to provide these arguments as a dictionary of strings, 
### using the "params" keyword argument. # set parameter of search for hotel
###    params = {"radius":5000, "type":"lodging", "key": g_key}

In [11]:
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [12]:
# Remove rows from hotel_df DataFrame that do NOT have values in "Hotel Name" column.
clean_hotel_df = hotel_df[(hotel_df["Hotel Name"]!="")]
clean_hotel_df.head(50)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hardoi,IN,82.74,clear sky,27.4167,80.1167,Hotel Rama Palace -Best Hotel /Best Restaurant...
1,Adamstown,PN,62.42,light rain,-25.0660,-130.1015,Down Alwyn's
3,Bel Ombre,SC,80.44,scattered clouds,-4.6167,55.4167,Coral Strand Smart Choice Hotel
4,Olyokminsk,RU,57.79,few clouds,60.3736,120.4264,"Gostinitsa ""Kolos"""
6,Enewetak,MH,83.59,overcast clouds,11.3474,162.3373,Enewetak Atoll
7,Altamont,US,67.78,haze,42.2068,-121.7372,Microtel Inn & Suites by Wyndham Klamath Falls
10,Badger,US,62.82,broken clouds,64.8000,-147.5333,Fairbanks / Chena River KOA
11,Kodiak,US,56.71,scattered clouds,57.7900,-152.4072,Best Western Kodiak Inn
12,Yellowknife,CA,78.42,smoke,62.4560,-114.3525,The Explorer Hotel
15,Vilyuysk,RU,59.13,few clouds,63.7553,121.6247,Gostinitsa Viliuisk
16,Mugia,ES,71.17,overcast clouds,43.1041,-9.2179,Hotel O Parranda
18,Bredasdorp,ZA,65.16,clear sky,-34.5322,20.0403,Wheatlands Lodge - Bredasdorp
21,Tazacorte,ES,76.17,few clouds,28.6290,-17.9293,Valle Aridane
22,Hermanus,ZA,68.70,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
23,Belyy Yar,RU,60.69,scattered clouds,53.6039,91.3903,Pasportnyy Stol
24,Tadine,NC,70.30,overcast clouds,-21.5500,167.8833,Accueil en tribu chez Aude et Jean
25,Avarua,CK,71.65,few clouds,-21.2078,-159.7750,Paradise Inn
26,La Ronge,CA,68.25,smoke,55.1001,-105.2842,Northland Motor Hotel
27,Mount Pearl,CA,72.45,broken clouds,47.5166,-52.7813,Ramada by Wyndham St. John's
30,Bandarbeyla,SO,78.40,overcast clouds,9.4942,50.8122,JABIR HOTEL
31,Caleta De Carquin,PE,71.74,clear sky,-11.0925,-77.6267,Hotel Villa Kitzia Huacho
32,Atafu Village,TK,82.54,broken clouds,-8.5421,-172.5159,Atafu Village
34,Tafuna,AS,78.75,broken clouds,-14.3358,-170.7200,Tradewinds Hotel
35,Tobruk,LY,81.91,clear sky,32.0836,23.9764,عقار الحاج منفور علي.
36,College,US,62.80,broken clouds,64.8569,-147.8028,Pike's Waterfront Lodge
37,Porto Torres,IT,71.78,scattered clouds,40.8350,8.3972,Hotel Elisa
40,Nchelenge,ZM,76.21,overcast clouds,-9.3451,28.7340,KD Travellers Home
42,Bonthe,SL,79.00,light rain,7.5264,-12.5050,Bonthe Holiday Village
43,Stanley,GB,58.59,few clouds,54.8680,-1.6985,Beamish Hall Hotel
47,Hawaiian Paradise Park,US,78.03,moderate rain,19.5933,-154.9731,Casa by the Sea
48,Qusmuryn,KZ,51.84,broken clouds,52.4503,64.6311,Депоның қонақ үйі
50,Chirala,IN,83.14,few clouds,15.8167,80.3500,Bala Residency
56,Bethel,US,79.77,broken clouds,41.3712,-73.4140,Courtyard by Marriott Danbury
57,Tiksi,RU,50.58,overcast clouds,71.6872,128.8694,Arktika
58,Portland,US,71.53,overcast clouds,45.5234,-122.6762,Embassy Suites by Hilton Portland Downtown
59,El Granada,US,84.92,haze,37.5027,-122.4694,Beach House Hotel
62,Susuman,RU,51.80,broken clouds,62.7833,148.1667,Susumanzoloto
63,Necochea,AR,60.82,few clouds,-38.5473,-58.7368,Hotel Tres Arroyos
64,Antonio Enes,MZ,72.66,few clouds,-16.2325,39.9086,Guest House HESADA
66,Port Mathurin,MU,72.88,clear sky,-19.6833,63.4167,Ti Pavillon
67,Hasaki,JP,77.31,overcast clouds,35.7333,140.8333,Inubosaki Kanko Hotel
69,Yuzhno-Kurilsk,RU,58.69,scattered clouds,44.0306,145.8556,Guesthouse Berloga
71,Hithadhoo,MV,81.37,broken clouds,-0.6000,73.0833,Scoop Guest House
72,Jamestown,US,82.02,scattered clouds,42.0970,-79.2353,Hampton Inn & Suites Jamestown
74,Saint-Denis,FR,66.51,light rain,48.9167,2.3333,ibis budget Paris Porte de Montmartre
75,Port Elizabeth,ZA,61.09,clear sky,-33.9180,25.5701,39 On Nile Guest House
76,Holualoa,US,78.78,scattered clouds,19.6228,-155.9522,Royal Kona Resort
77,Lebu,CL,51.60,overcast clouds,-37.6167,-73.6500,Hosteria Millaneco
78,Udachny,RU,61.47,overcast clouds,66.4167,112.4000,Severnoye Siyaniye
79,Taksimo,RU,56.91,clear sky,56.3444,114.8794,"Gostinitsa ""Domashniy Ochag"""

In [13]:
len(clean_hotel_df)

371

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

## Create a Maximum Temperature Heatmap from hotel_df DataFrame with pop-ups

In [15]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

In [16]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [17]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))